### ISSUE TITLE
Get access to the other texture surfaces

### ISSUE THREAD

**Issue by WizzardMaker** [nyfrk/S4ModApi#7]
Is it possible to maybe get access to all the surfaces the game uses?
Like the menu bar on the left or the mini map?

Or at least get access to each individual draw call of these major elements (Especially the chat box or the info box)

I would like to refine the chat box and reposition the building info box.
I also want to be able to arbitrarily redraw the to the screen at "any" time. (Used for my HD Patch. This should circumvent the need to use rgb565 in a surface, as we can just draw our textures to the screen at the end of the frame and then redraw all occluded menu items on top)

**Comment by nyfrk** [comment]
> Is it possible to maybe get access to all the surfaces the game uses?
> Like the menu bar on the left or the mini map?

That should be possible. Although I have not looked into details yet.
The minimap is definitely possible. I already reversed some parts of the minimap render functions.

> Or at least get access to each individual draw call of these major elements (Especially the chat box or the info box)

Such that you could let the game skip the rendering of these elements (eg to free space to render something yourself)?
Or would you just like to call these draw calls yourself to render the game elements onto your own surface?

> I would like to refine the chat box and reposition the building info box.
I also want to be able to arbitrarily redraw the to the screen at "any" time. (Used for my HD Patch. This should circumvent the need to use rgb565 in a surface, as we can just draw our textures to the screen at the end of the frame and then redraw all occluded menu items on top)

It would probably be better/easier just to realloc the rgb565 buffer to a rgb888 buffer. This would come with the advantage that we do not have to replace all game textures to rgb888. I already verified that this is possible. Although I have not implemented anything for this yet. 

In regard to the ui elements of the game it should be possible find the UI element struct of each element and adjust the x,y,w,h values for each of them. The necessary [struct](https://github.com/nyfrk/S4ModApi/blob/master/S4ModApi/s4.h) is already reversed. However, we just need to find the offsets of the elements you wish to alter. The ui elements are organised in a hierarchical way. So that is what some of the unknown fields are for. 

I am not sure if i can find the time to work on this in the next weeks. Pull Requests are really welcome.

**Comment by WizzardMaker** [comment]
> Such that you could let the game skip the rendering of these elements (eg to free space to render something yourself)?
Or would you just like to call these draw calls yourself to render the game elements onto your own surface?

Both would be great
Something like the way object rendering is handled. Have a callback for UI Element rendering and I can choose to render it or not

**Comment by WizzardMaker** [comment]
Is there a possible ETA on this issue?

It would be great to have that callback proc.

**Comment by nyfrk** [comment]
Unfurunatly no. However, i already reversed some of it for other purposes.

UI Components Rendering happens here. the arguments to call dword ptr [esi+18] are source rect, dest rect etc (i did not document the order, but you will probably quickly work that out):

```
S4_Main.exe+2647E1 - 8D 80 B8466E01        - lea eax,[eax+S4_Main.exe+11F46B8]
S4_Main.exe+2647E7 - 50                    - push eax
S4_Main.exe+2647E8 - FF 56 18              - call dword ptr [esi+18]
S4_Main.exe+2647EB - 85 C0                 - test eax,eax
```

If you want to skip the rendering of a component this would be a good place to set a hook. Fell free to implement it yourself. I will surely accept a merge request.

**Comment by nyfrk** [comment]
I added a [GuiBltHook](https://github.com/nyfrk/S4ModApi/blob/master/S4ModApi/CGuiBltHook.cpp). 

Moving just the surfaces to other positions will just be a visual change. Clicks to the buttons will still be registered only by clicking onto its old position. I think Viciten already reversed the structs for the UI components. It is probably better to just use these. 

If you want to be able to move the surfaces, cast the surfaces to IDirectDrawSurface7* and use the Blt method to do the blitting yourself. Then let the hook return 1 such that the original blitting is skipped.

**Comment by WizzardMaker** [comment]
Thank you so very much!

But I think there is a bug in the code, at least in the params. The rects are wrong and the srcSurface and dstSurface aren't IDirectDrawSurface7*
![image](https://user-images.githubusercontent.com/7768485/108632132-9a111480-746d-11eb-8c53-b2d981f181b3.png)

**Comment by nyfrk** [comment]
[I forgot to remove the edx push](https://github.com/nyfrk/S4ModApi/commit/207dcff9935b86cb27340f5e7fb7d96ee6a85d8f). It should work now.

**Comment by WizzardMaker** [comment]
Okay, this is a bit weird. The srcSurface doesn't seem to be a IDirectDrawSurface7?
![image](https://user-images.githubusercontent.com/7768485/108640762-ce032e80-749b-11eb-95ce-f53ace022956.png)

The vTable of that object points to S4_Main functions apparently.

I get an access violation exception, when trying to use any of the IDirectDrawSurface7 functions [notably the GetDC function]

**Comment by nyfrk** [comment]
It may be a wrapper for the DirectDrawSurface. Probably because the game supports multiple versions of DirectDraw. In that case we will have to reverse the wrapper struct. The struct seems to be simple though. I will have a look at it.

**Comment by WizzardMaker** [comment]
Yes, that solved the problem! Thank you very much
